# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests | Specifies the root directory of your project where the package.json file is located.
    schedule: # Update schedule for the package ecosystem | Specifies the update schedule. In this case, it is set to check for updates weekly.
      interval: "monthly"
